/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gms;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author poojitha
 */
public class deletePlantTesting extends javax.swing.JFrame {

    /**
     * Creates new form deletePlantTesting
     */
    String id;
    public deletePlantTesting(String i) {
        initComponents();
       this.id=i;
        try {
                Connection con=getConnection();
                Statement s=con.createStatement();
                String sql="select * from planttesting where crop_id='"+id+"'";
                ResultSet rs=s.executeQuery(sql);
                if(rs.next())
                {   
                   jL1.setText(rs.getString(2));
                   jL2.setText(String.valueOf(rs.getFloat(3)));
                   jL3.setText(rs.getString(4));
                   jL20.setText(rs.getString(5));
                   jL14.setText(rs.getString(6));
                   jL19.setText(rs.getString(7));
                   jL15.setText(rs.getString(8));
                   jL16.setText(String.valueOf(rs.getInt(9)));
                   jL17.setText(rs.getString(10));
                   jL29.setText(rs.getString(11));
                   jL30.setText(rs.getString(12));
                   jL31.setText(rs.getString(13));
                   jL32.setText(rs.getString(14));
                   jL33.setText(rs.getString(15));
                   jL35.setText(rs.getString(16));
                   jL18.setText(rs.getString(17));
                   jL38.setText(rs.getString(18));
                   jL39.setText(rs.getString(19));
                   jL34.setText(String.valueOf(rs.getFloat(20)));
                }
            }
            catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PlantTesting.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();
        jL15 = new javax.swing.JLabel();
        jL16 = new javax.swing.JLabel();
        jL17 = new javax.swing.JLabel();
        jL18 = new javax.swing.JLabel();
        jL19 = new javax.swing.JLabel();
        jL20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jL29 = new javax.swing.JLabel();
        jL30 = new javax.swing.JLabel();
        jL31 = new javax.swing.JLabel();
        jL32 = new javax.swing.JLabel();
        jL33 = new javax.swing.JLabel();
        jL34 = new javax.swing.JLabel();
        jL35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jL38 = new javax.swing.JLabel();
        jL39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(154, 227, 232));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Growth habit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 40, 155, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Leaflet size");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 79, 155, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Stem");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 154, 155, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Flower on main axis");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 193, 155, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Flower on side branches");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 229, 155, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Infloroscence");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 265, 155, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Time of maturity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 301, 155, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Pod constriction");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 337, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Leaflet color");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 112, 155, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Shelling percentage");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 155, 30));

        bDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDelete.setForeground(new java.awt.Color(102, 102, 102));
        bDelete.setText("Delete Above Crop Data");
        bDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 265, 33));

        jL1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 43, 200, 18));

        jL2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 79, 200, 18));

        jL3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 112, 200, 21));

        jL14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL14, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 193, 200, 21));

        jL15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL15, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 268, 200, 21));

        jL16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL16, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 301, 200, 21));

        jL17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL17, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 337, 200, 21));

        jL18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 200, 21));

        jL19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL19, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 235, 200, 21));

        jL20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL20.setAutoscrolls(true);
        jL20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jL20, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 160, 200, 21));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Pod reticulation");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 373, 155, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Number of kernels");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 155, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Presence of beak");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 155, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Testa color");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 155, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Kernel:color of testa");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 155, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Kernel shape");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 155, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Fresh seed dormacy");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 155, 30));

        jL29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL29, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 382, 200, 21));

        jL30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 200, 21));

        jL31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 200, 21));

        jL32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 200, 21));

        jL33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 200, 21));

        jL34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 200, 21));

        jL35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 200, 21));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Oil percentage");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 155, 30));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Weight of 100 kernels");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 155, 30));

        jL38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL38, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 200, 21));

        jL39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jL39, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 200, 21));

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        int result=JOptionPane.showConfirmDialog(this, "Delete?", "Delete Confirmation",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {

            try {
                Connection con=getConnection();
                PreparedStatement ps;
                String sql="delete from planttesting where crop_id='"+id+"'";
                ps = (PreparedStatement) con.prepareStatement(sql);
                int rowsDeleted=ps.executeUpdate();
                if(rowsDeleted>0)
                {   dispose();
                    JOptionPane.showMessageDialog(this, "Data deleted successfully");

                }else{
                    JOptionPane.showMessageDialog(this,"Sorry the data doesn't exist");
                }
            }
            catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Cropdetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
     public static Connection getConnection()throws SQLException, ClassNotFoundException
    {
         String url="jdbc:mysql://localhost:3306/GMS";
            String user="root";
            String pass="Poojitha@123";
            
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection(url, user, pass);
                return con;
            
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletePlantTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletePlantTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletePlantTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletePlantTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletePlantTesting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL15;
    private javax.swing.JLabel jL16;
    private javax.swing.JLabel jL17;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL19;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL20;
    private javax.swing.JLabel jL29;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL30;
    private javax.swing.JLabel jL31;
    private javax.swing.JLabel jL32;
    private javax.swing.JLabel jL33;
    private javax.swing.JLabel jL34;
    private javax.swing.JLabel jL35;
    private javax.swing.JLabel jL38;
    private javax.swing.JLabel jL39;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
